-- copied over from the LFT addon, can't hook the local table there
TURTLE_DUNGEON_CODES = {
    ['Ragefire Chasm'] = { code = 'rfc', isMainUpdated = false, isBrowseUpdated=false },
    ['Wailing Caverns'] = { code = 'wc', isMainUpdated = false, isBrowseUpdated=false },
    ['The Deadmines'] = { code = 'dm', isMainUpdated = false, isBrowseUpdated=false },
    ['Shadowfang Keep'] = { code = 'sfk', isMainUpdated = false, isBrowseUpdated=false },
    ['The Stockade'] = { code = 'stocks', isMainUpdated = false, isBrowseUpdated=false },
    ['Blackfathom Deeps'] = { code = 'bfd', isMainUpdated = false, isBrowseUpdated=false },
    ['Scarlet Monastery Graveyard'] = { code = 'smgy', isMainUpdated = false, isBrowseUpdated=false },
    ['Scarlet Monastery Library'] = { code = 'smlib', isMainUpdated = false, isBrowseUpdated=false },
    ['Gnomeregan'] = { code = 'gnomer', isMainUpdated = false, isBrowseUpdated=false },
    ['Razorfen Kraul'] = { code = 'rfk', isMainUpdated = false, isBrowseUpdated=false },
    ['The Crescent Grove'] = { code = 'tcg', isMainUpdated = false, isBrowseUpdated=false },
    ['Scarlet Monastery Armory'] = { code = 'smarmory', isMainUpdated = false, isBrowseUpdated=false },
    ['Scarlet Monastery Cathedral'] = { code = 'smcath', isMainUpdated = false, isBrowseUpdated=false },
    ['Razorfen Downs'] = { code = 'rfd', isMainUpdated = false, isBrowseUpdated=false },
    ['Uldaman'] = { code = 'ulda', isMainUpdated = false, isBrowseUpdated=false },
    ['Zul\'Farrak'] = { code = 'zf', isMainUpdated = false, isBrowseUpdated=false },
    ['Maraudon Orange'] = { code = 'maraorange', isMainUpdated = false, isBrowseUpdated=false },
    ['Maraudon Purple'] = { code = 'marapurple', isMainUpdated = false, isBrowseUpdated=false },
    ['Maraudon Princess'] = { code = 'maraprincess', isMainUpdated = false, isBrowseUpdated=false },
    ['Temple of Atal\'Hakkar'] = { code = 'st', isMainUpdated = false, isBrowseUpdated=false },
    ['Blackrock Depths'] = { code = 'brd', isMainUpdated = false, isBrowseUpdated=false },
    ['Blackrock Depths Arena'] = { code = 'brdarena', isMainUpdated = false, isBrowseUpdated=false },
    ['Blackrock Depths Emperor'] = { code = 'brdemp', isMainUpdated = false, isBrowseUpdated=false },
    ['Lower Blackrock Spire'] = { code = 'lbrs', isMainUpdated = false, isBrowseUpdated=false },
    ['Dire Maul East'] = { code = 'dme', isMainUpdated = false, isBrowseUpdated=false },
    ['Dire Maul North'] = { code = 'dmn', isMainUpdated = false, isBrowseUpdated=false },
    ['Dire Maul West'] = { code = 'dmw', isMainUpdated = false, isBrowseUpdated=false },
    ['Scholomance'] = { code = 'scholo', isMainUpdated = false, isBrowseUpdated=false },
    ['Stratholme: Undead District'] = { code = 'stratud', isMainUpdated = false, isBrowseUpdated=false },
    ['Stratholme: Scarlet Bastion'] = { code = 'stratlive', isMainUpdated = false, isBrowseUpdated=false },
    ['Karazhan Crypt'] = { code = 'kc', isMainUpdated = false, isBrowseUpdated=false },
    ['Caverns of Time: Black Morass'] = { code = 'cotbm', isMainUpdated = false, isBrowseUpdated=false },
    ['Stormwind Vault'] = { code = 'swv', isMainUpdated = false, isBrowseUpdated=false },
    ['Hateforge Quarry'] = { code = 'hfq', isMainUpdated = false, isBrowseUpdated=false }
}